version: 0.2

env:
  variables:
    STACK_NAME: "cloud-course-stack"
    AWS_REGION: "eu-west-1"
    ADMIN_EMAIL: mohamadyasser0801@gmail.com

phases:
  install:
    commands:
      - pip3 install aws-sam-cli
      - set -euo pipefail
      
  pre_build:
    commands:
      - sam --version
  build:
    commands:
      - sam build --use-container
  post_build:
    commands:
      - sam deploy
        --no-confirm-changeset
        --stack-name $STACK_NAME
        --region $AWS_REGION
        --capabilities CAPABILITY_IAM
        --no-fail-on-empty-changeset
        --resolve-s3
        --parameter-overrides ProjectName=cloud-course AdminEmail=$ADMIN_EMAIL
